AcquisitionFrameRateAuto = "Off" #off
AcquisitionFrameRateEnabled = true
AcquisitionMode = "Continuous"
AcquisitionStatusSelector = "FrameTriggerWait"
ActivePageNumber = 0
ActivePageOffset = 0
ActivePageValue = 3435973836
#AutoExposureTimeLowerLimit = 39.99837281298824
#AutoExposureTimeUpperLimit = 110326.2528777122
AutoFunctionAOIsControl = "Off"
#AutoGainLowerLimit = 0.0
#AutoGainUpperLimit = 24.00007438659668
BinningVertical = 1
BlackLevel = 0.0
BlackLevelEnabled = true
ChunkEnable = false
ChunkModeActive = false
ChunkSelector = "FrameCounter"
#DeviceLinkThroughputLimit = 183040000
DeviceUserID = ""
EventNotification = "Off"
EventSelector = "ExposureEnd"
ExposureAuto = "Off"
ExposureMode = "Timed"
ExposureTime = 110000
GainAuto = "Off"
Gain = 1
Gamma = 1.25
GammaEnabled = true
Height = 2704
LineDebouncerTimeRaw = 0
LineMode = "Input"
LineSelector = "Line0"
OffsetX = 0
OffsetY = 0
OnBoardColorProcessEnabled = true
ParameterSelector = "Gain"
PixelFormat = "Mono16"
RemoveLimits = false
ReverseX = false
SharpnessAuto = "Continuous"
SharpnessEnabled = true
SingleFrameAcquisitionMode = "FreeRunning"
TLParamsLocked = 0
TestImageSelector = "Off"
TestPattern = "Off"
TestPendingAck = 0
TriggerActivation = "FallingEdge"
TriggerDelay = 0.0
TriggerDelayEnabled = false
TriggerMode = "Off"
TriggerSelector = "FrameStart"
TriggerSource = "Line0"
U3VAccessPrivilege = 0
U3VCPConfigurationHigh = 0
U3VCPConfigurationLow = 0
U3VDeviceConfigurationHigh = 0
U3VDeviceConfigurationLow = 0
U3VMessageChannelID = 0
UserOutputSelector = "UserOutputValue1"
UserSetDefault = "Default"
UserSetDefaultSelector = "Default"
UserSetSelector = "Default"
VideoMode = "Mode0"
Width = 3376
pgrAutoExposureCompensationLowerLimit = 0.4150390625
pgrAutoExposureCompensationUpperLimit = 2.0
pgrCurrentCorrectedPixelCount = 13
pgrCurrentCorrectedPixelIndex = 0
pgrCurrentCorrectedPixelOffsetX = 262
pgrCurrentCorrectedPixelOffsetY = 668
pgrDefectPixelCorrectionEnable = true
pgrDefectPixelCorrectionTestMode = "Off"
pgrDevicePowerSupplySelector = "External"
pgrExposureCompensationAuto = "Off"
